### PR TITLE
0.7 compat (attempt 3)

### PR DESCRIPTION
**Pull request by oxinabox**

### CODE REVIEW

**Comment by oxinabox** [comment]
I am going to hold-off on merging this til someone pokes me, 
or until 0.7-release-candidate1 comes out.

**Comment by CarloLucibello** [comment]
and here is the poke :)

I think you should remove the Manifest.toml, and just add a Project.toml

Test are passing on last nightly, but I see a few warnings:
```julia
Test Summary: | Pass  Total
util          |    5      5
Test Summary: | Pass  Total
locations     |    2      2
┌ Warning: `foldr(op, v0, itr)` is deprecated, use `foldr(op, itr; init=v0)` instead.
│   caller = @match(::LineNumberNode, ::Module, ::Any, ::Any) at macro.jl:54
└ @ MacroTools ~/.julia/packages/MacroTools/IEXI/src/macro.jl:54
┌ Warning: Could not resolve filename due to
└ @ DataDeps ~/.julia/dev/DataDeps/src/filename_solving.jl:14
┌ Warning: HTTP.ExceptionRequest.StatusError(404, HTTP.Messages.Response:
│ """
│ HTTP/1.1 404 Not Found
│ Cache-Control: max-age=604800
│ Content-Type: text/html
│ Date: Mon, 16 Jul 2018 09:06:21 GMT
│ Expires: Mon, 23 Jul 2018 09:06:21 GMT
│ Server: EOS (vny006/0451)
│ Vary: Accept-Encoding
│ Content-Length: 1270
│ 
│ """)
└ @ DataDeps ~/.julia/dev/DataDeps/src/filename_solving.jl:15
┌ Warning: falling back to using final part of remotepath
└ @ DataDeps ~/.julia/dev/DataDeps/src/filename_solving.jl:16
Test Summary: | Pass  Total
main          |    4      4
┌ Warning: Could not resolve filename due to
└ @ DataDeps ~/.julia/dev/DataDeps/src/filename_solving.jl:14
┌ Warning: ErrorException("PCRE.exec error: UTF-8 error: byte 2 top bits not 0x80")
└ @ DataDeps ~/.julia/dev/DataDeps/src/filename_solving.jl:15
┌ Warning: falling back to using final part of remotepath
└ @ DataDeps ~/.julia/dev/DataDeps/src/filename_solving.jl:16
Test Summary:    | Pass  Broken  Total
filename_solving |    8       1      9
[ Info: sending all datadeps to /tmp/tmpibSaeq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10001    0 10001    0     0  17037      0 --:--:-- --:--:-- --:--:-- 17008
┌ Warning: Checksum not provided, add to the Datadep Registration the following hash line
└ @ DataDeps ~/.julia/dev/DataDeps/src/verification.jl:38
┌ Warning: "1f08958df70c30bbf3f7205ad5f9b2b9430e3378b4e4e6300063bd9fbd83d6e3"
└ @ DataDeps ~/.julia/dev/DataDeps/src/verification.jl:40
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  874k  100  874k    0     0   116k      0  0:00:07  0:00:07 --:--:--  150k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 72985    0 72985    0     0   141k      0 --:--:-- --:--:-- --:--:--  141k
nonmentions_realDonaldTrump_poll_tweets.csv┌ Warning: broadcast will default to iterating over its arguments in the future. Wrap arguments of
│ type `x::Char` with `Ref(x)` to ensure they broadcast as "scalar" elements.
│   caller = ip:0x0
└ @ Core :-1
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28881  100 28881    0     0  62377      0 --:--:-- --:--:-- --:--:-- 62377
100 9680k  100 9680k    0     0  1447k      0  0:00:06  0:00:06 --:--:-- 1796k
┌ Warning: Checksum not provided, add to the Datadep Registration the following hash line
└ @ DataDeps ~/.julia/dev/DataDeps/src/verification.jl:38
┌ Warning: "715d99f57999dfd174baa6c32e67e5eaf438a315273c0889ac8cdbfc83421355"
└ @ DataDeps ~/.julia/dev/DataDeps/src/verification.jl:40
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  565k  100  565k    0     0   189k      0  0:00:02  0:00:02 --:--:--  189k
100  434k  100  434k    0     0   136k      0  0:00:03  0:00:03 --:--:--  136k
Archive:  /tmp/tmpibSaeq/UCI Banking/bank.zip
  inflating: bank-full.csv           Archive:  /tmp/tmpibSaeq/UCI Banking/bank-additional.zip
   creating: bank-additional/
  inflating: bank-additional/.DS_Store  
   creating: __MACOSX/
...
```

**Comment by oxinabox** [comment]
Alright,
I will finish and merge #54, 
and rebase this,

I think the deprecation is not my fault.
That PCRE error is a worry though

**Comment by oxinabox** [comment]
@CarloLucibello  I have fixed all the warnings that matter.
For reasons the tests are ment to show some warnings as they are testing the warning behavour

**Pull request merged**
